apiVersion: v1
kind: Service
metadata:
  labels:
    app: apt-cacher
  name: proxy
spec:
  type: LoadBalancer
  ports:
  - name: "proxy"
    port: 3142
    targetPort: 3142
    protocol: TCP
  selector:
    app: apt-cacher